# Generated by Django 4.2.3 on 2023-07-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_location_textblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
