# Generated by Django 4.2.3 on 2023-07-18 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_user_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textblock',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='textblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
