# Generated by Django 4.2.3 on 2023-07-18 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_course_alter_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
