# Generated by Django 4.2.3 on 2023-07-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_textblock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='is_user',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
