# Generated by Django 4.2.3 on 2023-08-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_textblock_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textblock',
            name='grade',
        ),
    ]
